### ISSUE TITLE
Does not install sg3-utils during install on Linux Mint 18.3

### ISSUE THREAD

**Issue by kasamikona** [Zibri/LG-DVD-REGION-RESET#1]
Prerequisite checking somehow thinks sg3-utils package is installed when it isn't. Results in 'device not found' error, resolved by installing manually. Installation was tried both as user and root.

**Comment by Zibri** [comment]
Ok.. I corrected it. Uninstall sg3 utils and try again...

**Comment by kasamikona** [comment]
Working perfectly now, thanks.
